pipelines:
  default:
    - step:
        image: python:latest
        caches:
          - pip
        script:
          - pip install .
    - step:
        image: python:windowsservercore
        caches:
          - pip
        script:
          - pip install .
